[package]
name = "reflector-client"
version = "0.1.8"
edition = "2024"
repository = "https://github.com/rodolfovillaruz/reflector-client"

[dependencies]
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
webpki-roots = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
